import React, { useEffect, useState } from 'react';
import { apiFetch } from './api';
import { ShieldCheck, Plus, Pencil, Trash2, RefreshCw, LogOut, Activity, Users, ArrowDownToLine, ScrollText } from 'lucide-react';

type Address = { id:string; asset:string; network:string; address:string; label?:string; minDeposit:number|string; instructions?:string; enabled:boolean };
type Feature = { key:string; enabled:boolean };

const FEATURES = ['deposits','withdrawals','trading','p2p','buySell','convert','earn','rewards','referrals','kyc'];

export const AdminView: React.FC = () => {
  const [loggedIn, setLoggedIn] = useState(Boolean(sessionStorage.getItem('kroma_admin_session')));
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error,setError]=useState('');
  const [addresses,setAddresses]=useState<Address[]>([]); const [features,setFeatures]=useState<Feature[]>([]); const [users,setUsers]=useState<any[]>([]); const [transactions,setTransactions]=useState<any[]>([]); const [logs,setLogs]=useState<any[]>([]); const [wallets,setWallets]=useState<any[]>([]); const [deposits,setDeposits]=useState<any[]>([]); const [withdrawals,setWithdrawals]=useState<any[]>([]);
  const [editing,setEditing]=useState<Address|null>(null); const [form,setForm]=useState({asset:'USDT',network:'TRC20',address:'',label:'',minDeposit:'0',instructions:'',enabled:true});

  const load=async()=>{ try { const [a,f,u,t,l,w,d,wd]=await Promise.all([apiFetch<any>('/api/admin/deposit-addresses'),apiFetch<any>('/api/admin/features'),apiFetch<any>('/api/admin/users'),apiFetch<any>('/api/admin/transactions'),apiFetch<any>('/api/admin/audit-logs'),apiFetch<any>('/api/admin/wallets'),apiFetch<any>('/api/admin/deposits'),apiFetch<any>('/api/admin/withdrawals')]); setAddresses(a.addresses); setFeatures(f.features); setUsers(u.users); setTransactions(t.transactions); setLogs(l.logs); setWallets(w.wallets); setDeposits(d.deposits); setWithdrawals(wd.withdrawals); setError(''); } catch(e:any){ setError(e.message); } };
  useEffect(()=>{if(loggedIn) load();},[loggedIn]);

  const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const r=await apiFetch<any>('/api/admin/login',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('kroma_admin_session','1');setLoggedIn(true);setPassword('');}catch(e:any){setError(e.message)}};
  const logout=async()=>{try{await apiFetch('/api/admin/logout',{method:'POST'})}catch{}sessionStorage.removeItem('kroma_admin_session');sessionStorage.removeItem('kroma_admin_token');setLoggedIn(false)};
  const save=async()=>{try{const body={...form,minDeposit:Number(form.minDeposit)||0}; if(editing) await apiFetch(`/api/admin/deposit-addresses/${editing.id}`,{method:'PUT',body:JSON.stringify(body)}); else await apiFetch('/api/admin/deposit-addresses',{method:'POST',body:JSON.stringify(body)});setEditing(null);setForm({asset:'USDT',network:'TRC20',address:'',label:'',minDeposit:'0',instructions:'',enabled:true});await load();}catch(e:any){setError(e.message)}};
  const remove=async(id:string)=>{if(!confirm('Delete this deposit address?'))return;try{await apiFetch(`/api/admin/deposit-addresses/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}};
  const toggle=async(f:Feature)=>{try{await apiFetch(`/api/admin/features/${f.key}`,{method:'PUT',body:JSON.stringify({enabled:!f.enabled})});await load()}catch(e:any){setError(e.message)}};

  if(!loggedIn) return <div className="min-h-screen bg-[#070A10] flex items-center justify-center p-4 text-slate-100"><form onSubmit={login} className="w-full max-w-md bg-[#111622] border border-slate-700 rounded-2xl p-7 shadow-2xl"><div className="flex items-center gap-3 mb-6"><div className="p-3 rounded-xl bg-cyan-500/10 text-cyan-400"><ShieldCheck/></div><div><h1 className="text-xl font-bold">Admin Control Center</h1><p className="text-xs text-slate-400">Secure server-side administration</p></div></div><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" className="w-full mb-3 p-3 rounded-lg bg-slate-900 border border-slate-700"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" className="w-full mb-4 p-3 rounded-lg bg-slate-900 border border-slate-700"/><button className="w-full py-3 rounded-lg bg-cyan-400 text-slate-950 font-bold">Sign in</button>{error&&<p className="text-red-400 text-sm mt-3">{error}</p>}</form></div>;

  return <div className="min-h-screen bg-[#070A10] text-slate-100 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-6"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 className="text-2xl md:text-3xl font-bold">Admin Control Center</h1><p className="text-sm text-slate-400 mt-1">Monitor and control the live platform configuration.</p></div><div className="flex gap-2"><button onClick={load} className="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700"><RefreshCw className="w-4 h-4 inline mr-2"/>Refresh</button><button onClick={logout} className="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700"><LogOut className="w-4 h-4 inline mr-2"/>Logout</button></div></div>{error&&<div className="p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300">{error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat icon={<Users/>} label="Users" value={users.length}/><Stat icon={<Activity/>} label="Transactions" value={transactions.length}/><Stat icon={<ArrowDownToLine/>} label="Deposit Addresses" value={addresses.filter(a=>a.enabled).length}/><Stat icon={<ScrollText/>} label="Audit Events" value={logs.length}/></div>
  <section className="bg-[#111622] border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-lg mb-4">Frontend Feature Controls</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{FEATURES.map(k=>{const f=features.find(x=>x.key===k)||{key:k,enabled:true};return <button key={k} onClick={()=>toggle(f)} className={`p-3 rounded-xl border text-left ${f.enabled?'border-emerald-500/30 bg-emerald-500/10':'border-red-500/30 bg-red-500/10'}`}><div className="text-sm font-semibold">{k}</div><div className={`text-xs mt-1 ${f.enabled?'text-emerald-400':'text-red-400'}`}>{f.enabled?'Enabled':'Disabled'}</div></button>})}</div></section>
  <section className="bg-[#111622] border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-lg">Deposit Wallet Addresses</h2><p className="text-xs text-slate-400">Users receive the active address from the server.</p></div><button onClick={()=>{setEditing(null);setForm({asset:'USDT',network:'TRC20',address:'',label:'',minDeposit:'0',instructions:'',enabled:true})}} className="px-3 py-2 rounded-lg bg-cyan-400 text-slate-950 font-bold"><Plus className="w-4 h-4 inline mr-1"/>Add Address</button></div>
  {(editing!==null || form.address==='') && <div className="grid md:grid-cols-2 gap-3 p-4 mb-5 rounded-xl bg-slate-900 border border-slate-800"><Field label="Asset"><input value={form.asset} onChange={e=>setForm({...form,asset:e.target.value})} className="input"/></Field><Field label="Network"><input value={form.network} onChange={e=>setForm({...form,network:e.target.value})} className="input"/></Field><Field label="Wallet Address"><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="input"/></Field><Field label="Label"><input value={form.label} onChange={e=>setForm({...form,label:e.target.value})} className="input"/></Field><Field label="Minimum Deposit"><input type="number" min="0" value={form.minDeposit} onChange={e=>setForm({...form,minDeposit:e.target.value})} className="input"/></Field><Field label="Instructions"><input value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} className="input"/></Field><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Active</label><div className="md:text-right"><button onClick={save} className="px-4 py-2 rounded-lg bg-emerald-400 text-slate-950 font-bold">{editing?'Save Changes':'Create Address'}</button>{editing&&<button onClick={()=>setEditing(null)} className="ml-2 px-4 py-2 rounded-lg bg-slate-800">Cancel</button>}</div></div>}
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-slate-400 border-b border-slate-800"><th className="text-left p-3">Asset</th><th className="text-left p-3">Network</th><th className="text-left p-3">Address</th><th className="text-left p-3">Min</th><th className="text-left p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{addresses.map(a=><tr key={a.id} className="border-b border-slate-800/70"><td className="p-3 font-bold">{a.asset}</td><td className="p-3">{a.network}</td><td className="p-3 font-mono text-xs max-w-xs break-all">{a.address}</td><td className="p-3">{String(a.minDeposit)}</td><td className="p-3">{a.enabled?<span className="text-emerald-400">Active</span>:<span className="text-red-400">Disabled</span>}</td><td className="p-3 flex justify-end gap-2"><button onClick={()=>{setEditing(a);setForm({asset:a.asset,network:a.network,address:a.address,label:a.label||'',minDeposit:String(a.minDeposit),instructions:a.instructions||'',enabled:a.enabled})}} className="p-2 bg-slate-800 rounded"><Pencil className="w-4 h-4"/></button><button onClick={()=>remove(a.id)} className="p-2 bg-red-500/10 text-red-400 rounded"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></section>
  <section className="grid lg:grid-cols-2 gap-6"><Data title="Recent Users" rows={users} cols={['email','status','kycStatus']}/><Data title="Recent Transactions" rows={transactions} cols={['type','asset','amount','status']}/></section><section className="grid lg:grid-cols-3 gap-6"><Data title="Wallet Ledger Balances" rows={wallets} cols={['email','asset','accountType','available','locked']}/><Data title="Pending Deposits" rows={deposits} cols={['email','asset','network','amount','status']}/><Data title="Withdrawal Queue" rows={withdrawals} cols={['email','asset','amount','status']}/></section>
  <section className="bg-[#111622] border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-lg mb-3">Audit Log</h2><div className="space-y-2 max-h-72 overflow-auto">{logs.map(l=><div key={l.id} className="p-3 rounded-lg bg-slate-900 text-xs"><span className="text-cyan-400">{l.action}</span> {l.entityType} <span className="text-slate-500">{new Date(l.createdAt).toLocaleString()}</span></div>)}</div></section>
  </div></div>;
};
const Stat=({icon,label,value}:{icon:React.ReactNode;label:string;value:number})=><div className="bg-[#111622] border border-slate-800 rounded-xl p-4"><div className="text-cyan-400 mb-2">{icon}</div><div className="text-2xl font-bold">{value}</div><div className="text-xs text-slate-400">{label}</div></div>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="text-xs text-slate-400 space-y-1"><span>{label}</span>{children}</label>;
const Data=({title,rows,cols}:{title:string;rows:any[];cols:string[]})=><section className="bg-[#111622] border border-slate-800 rounded-2xl p-5"><h2 className="font-bold text-lg mb-3">{title}</h2><div className="overflow-auto"><table className="w-full text-xs"><tbody>{rows.slice(0,20).map((r,i)=><tr key={i} className="border-b border-slate-800/70">{cols.map(c=><td key={c} className="p-2">{String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div></section>;
